version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-s0qsd8a7qklc --output-template-file package.yaml
artifacts:
  files:
    - package.yaml
